name: Push to Replicate
 
on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'xuxx/comfyui'
        required: true
 
jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Free disk pace
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false
 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.PAT_TOKEN }}
 
      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}
        
      - name: Push to Replicate
        run: cog push r8.im/${{ inputs.model_name }}